application: my-app-id
version: 1
runtime: python27
api_version: 1
threadsafe: true


handlers:
- url: /css
  static_dir: css
  
- url: /img
  static_dir: img
  
- url: /(.*\.js)
  mime_type: text/javascript
  static_files: js/\1
  upload: js/(.*\.js)
  http_headers:
    Access-Control-Allow-Origin: '*'
    Access-Control-Allow-Methods: GET, POST
    Access-Control-Allow-Headers: X-Custom
  
- url: /.*
  script: main.application
  
libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest